version: '3.9'

services:
  publisher_api:
    build: .
    ports: 
        - "8000:80"
    depends_on: 
        - db
        - rabbitmq
        - mongo-express
        - mongo
  rabbitmq: # login guest:guest
    image: rabbitmq:3-management
    hostname: "rabbitmq"
    labels:
      NAME: "rabbitmq"
    ports:
    - "4369:4369"
    - "5671:5671"
    - "5672:5672"
    - "25672:25672"
    - "15671:15671"
    - "15672:15672"
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
            SA_PASSWORD: "teste"
            ACCEPT_EULA: "Y"
            
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: teste
      ME_CONFIG_BASICAUTH_PASSWORD: teste123!
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: teste123!
    links:
      - mongo
    networks:
      - mongo-compose-network

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: teste123!
    ports:
      - "27017:27017"
    volumes:
      - /home/Teste/Desenvolvimento/Docker/Volumes/MongoDB:/data/db
    networks:
      - mongo-compose-network

networks: 
    mongo-compose-network:
      driver: bridge